/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

import { isTauri } from '@/lib/platform'

/**
 * Service-worker registration and update detection for the web build.
 *
 * The worker itself is generated by vite-plugin-pwa (`generateSW`) with
 * `registerType: 'prompt'`, which means it deliberately does NOT call
 * `skipWaiting()` or `clientsClaim()` on its own. A new build therefore installs
 * and then *waits*, leaving the running page on the bundle it started with —
 * swapping chunks under a live React tree would break the session. Handing over
 * is entirely this module's job, driven by the user pressing "Reload".
 *
 * Two consequences of the generated worker's shape drive the code below:
 *
 *  - It listens for a `{ type: 'SKIP_WAITING' }` message. That is the only way to
 *    promote the waiting worker.
 *  - It does not call `clientsClaim()`, so activating the new worker does not
 *    give it control of this already-loaded page. We must reload once the waiting
 *    worker reports `activated`; waiting on `controllerchange` alone would hang.
 */

/** Message the generated worker listens for in order to call `skipWaiting()`. */
export const skipWaitingMessage = { type: 'SKIP_WAITING' } as const

/** URL of the generated worker, and the scope it must control. */
export const serviceWorkerUrl = '/sw.js'

/** Background re-check cadence for a tab left open for days. */
export const updateCheckIntervalMs = 60 * 60 * 1000

/** Floor between `registration.update()` calls, so rapid tab switching on mobile
 *  does not turn the visibility hook into a request loop. */
export const updateCheckThrottleMs = 60 * 1000

/**
 * False for the Tauri builds, which ship the same `dist` but serve it through
 * the native shell and have their own updater (`use-desktop-update.ts`). A
 * worker there would shadow assets the webview already resolves locally.
 */
export const isServiceWorkerSupported = (): boolean =>
  typeof navigator !== 'undefined' && 'serviceWorker' in navigator && !isTauri()

/**
 * Promotes the waiting worker and reloads onto it.
 *
 * Resolves only after the reload has been requested, so callers can keep a
 * button in a pending state. If nothing is waiting there is no update to apply
 * and this is a no-op — the caller's prompt was stale.
 */
export const applyWaitingUpdate = (
  registration: ServiceWorkerRegistration,
  reload: () => void = () => window.location.reload(),
): void => {
  const waiting = registration.waiting
  if (!waiting) {
    return
  }

  // Reload once the new worker is live. `activated` is terminal, but a worker
  // that was already activated by another tab never fires `statechange` again,
  // so the current state is checked up front too.
  const reloadWhenActive = () => {
    if (waiting.state === 'activated') {
      reload()
      return true
    }
    return false
  }

  if (!reloadWhenActive()) {
    waiting.addEventListener('statechange', reloadWhenActive)
  }

  waiting.postMessage(skipWaitingMessage)
}

/** True when `worker` represents a *newer* build rather than the very first
 *  install. Without an existing controller there is no old bundle to replace,
 *  so an installed worker is just this page's first one — prompting there would
 *  ask the user to reload into what they are already running. */
const isUpdate = (container: ServiceWorkerContainer): boolean => container.controller !== null

export type RegisterServiceWorkerOptions = {
  /** Called when a new build is installed and waiting for the user's go-ahead. */
  onUpdateReady: () => void
  /** Injectable for tests; defaults to `navigator.serviceWorker`. */
  container?: ServiceWorkerContainer
}

/**
 * Registers the worker and reports when a newer build is ready to take over.
 *
 * Never throws: a failed registration (private mode, an unsupported browser, a
 * 404 on `/sw.js` behind a misconfigured proxy) must not stop the app booting —
 * the worker is an enhancement, not a dependency.
 */
export const registerServiceWorker = async ({
  onUpdateReady,
  container = navigator.serviceWorker,
}: RegisterServiceWorkerOptions): Promise<ServiceWorkerRegistration | undefined> => {
  try {
    const registration = await container.register(serviceWorkerUrl, { scope: '/' })

    // A worker can already be waiting from an earlier visit that was never
    // reloaded, in which case no `updatefound` will ever fire for it.
    if (registration.waiting && isUpdate(container)) {
      onUpdateReady()
    }

    registration.addEventListener('updatefound', () => {
      const installing = registration.installing
      if (!installing) {
        return
      }
      installing.addEventListener('statechange', () => {
        if (installing.state === 'installed' && isUpdate(container)) {
          onUpdateReady()
        }
      })
    })

    return registration
  } catch (error) {
    console.error('Service worker registration failed:', error)
    return undefined
  }
}

/**
 * Asks the browser to re-fetch `/sw.js` and compare it byte-for-byte with the
 * installed copy. Resolves false when the check could not run (offline, or the
 * browser rejected it) — the caller treats that as "no update found", never as
 * an error worth surfacing.
 */
export const checkForServiceWorkerUpdate = async (registration: ServiceWorkerRegistration): Promise<boolean> => {
  try {
    await registration.update()
    return true
  } catch {
    // Deliberately silent. This runs on a timer and on every foreground, and
    // being offline is the common failure — logging it would just spam the
    // console. The `false` return is the whole signal, and callers treat it as
    // "no update found" rather than as an error worth showing anyone.
    return false
  }
}

export type UpdatePollingOptions = {
  intervalMs?: number
  throttleMs?: number
  /** Injectable clock source for tests. */
  now?: () => number
}

/**
 * Polls for a new build while the app is open, and — more importantly for an
 * installed app on a phone — whenever it comes back to the foreground. A home
 * screen app is usually resumed rather than launched, so without the visibility
 * hook it could run a stale bundle for days between cold starts.
 *
 * Returns a teardown function.
 */
export const startUpdatePolling = (
  registration: ServiceWorkerRegistration,
  {
    intervalMs = updateCheckIntervalMs,
    throttleMs = updateCheckThrottleMs,
    now = () => Date.now(),
  }: UpdatePollingOptions = {},
): (() => void) => {
  let lastCheck = now()

  const check = () => {
    lastCheck = now()
    void checkForServiceWorkerUpdate(registration)
  }

  const checkIfStale = () => {
    if (now() - lastCheck >= throttleMs) {
      check()
    }
  }

  const onVisibilityChange = () => {
    if (document.visibilityState === 'visible') {
      checkIfStale()
    }
  }

  const interval = setInterval(check, intervalMs)
  document.addEventListener('visibilitychange', onVisibilityChange)

  return () => {
    clearInterval(interval)
    document.removeEventListener('visibilitychange', onVisibilityChange)
  }
}
