#!/bin/bash

echo "=== GitHub Actions Rust Caching Verification ==="
echo ""
echo "Test Commits:"
echo "- Initial Fix: bb28aa3 (Optimize Rust caching in CI workflow using Swatinem/rust-cache)"
echo "- Cache Test 1: 2a33842 (test: trigger CI to verify Rust caching effectiveness)"
echo "- Cache Test 2: 709bf8b (test: second cache test commit - no Rust changes)"
echo ""
echo "To check workflow runs after authenticating with 'gh auth login':"
echo ""
echo "# List recent runs for this branch"
echo "gh run list --branch cursor/fix-github-actions-rust-caching-0cbf --limit 10"
echo ""
echo "# Get detailed timing for specific runs"
echo "gh run view <RUN_ID> --json jobs"
echo ""
echo "Expected Results:"
echo "- First run (bb28aa3): ~9 minutes (populating cache)"
echo "- Second run (2a33842): 1-3 minutes (cache hit, no Rust changes)"
echo "- Third run (709bf8b): 1-3 minutes (cache hit, no Rust changes)"
echo ""
echo "To manually check: https://github.com/thunderbird/thunderbolt/actions"
echo "Look for runs on branch: cursor/fix-github-actions-rust-caching-0cbf"