//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "message")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i32,
    pub date: DateTimeUtc,
    pub subject: String,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub snippet: String,
    #[sea_orm(column_type = "Text")]
    pub clean_text: String,
    pub clean_text_tokens_in: i32,
    pub clean_text_tokens_out: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
