import type { LanguageModelV2StreamPart } from '@ai-sdk/provider'
import { describe, expect, it } from 'bun:test'
import { hermesToolMiddleware } from '@ai-sdk-tool/parser'

// Mock the FIXED Flower provider's stream format (only text-delta events)
const createFixedFlowerStream = (chunks: string[], streamId: string = 'flower-123-abc'): ReadableStream<LanguageModelV2StreamPart> => {
  return new ReadableStream({
    start(controller) {
      // Fixed Flower provider only emits text deltas (no text-start/text-end)
      for (const chunk of chunks) {
        controller.enqueue({
          type: 'text-delta',
          id: streamId,
          delta: chunk,
        })
      }
      
      controller.enqueue({
        type: 'finish',
        finishReason: 'stop',
        usage: {
          inputTokens: undefined,
          outputTokens: undefined,
          totalTokens: undefined,
        },
      })
      
      controller.close()
    },
  })
}

// Helper to collect stream parts
const collectStreamParts = async (stream: ReadableStream<LanguageModelV2StreamPart>): Promise<LanguageModelV2StreamPart[]> => {
  const parts: LanguageModelV2StreamPart[] = []
  const reader = stream.getReader()
  
  try {
    while (true) {
      const { done, value } = await reader.read()
      if (done) break
      parts.push(value)
    }
  } finally {
    reader.releaseLock()
  }
  
  return parts
}

describe('Fixed Flower + hermesToolMiddleware', () => {
  it('should have consistent IDs when Flower only emits text-delta events', async () => {
    const mockDoStream = async () => {
      const stream = createFixedFlowerStream(['Hi', ' Chris', '!', ' How', ' can', ' I', ' assist', ' you', ' today', '?'])
      return { stream }
    }

    // Apply hermesToolMiddleware to the fixed Flower stream
    const middleware = hermesToolMiddleware
    const wrappedResult = await middleware.wrapStream!({
      doStream: mockDoStream,
      doGenerate: async () => ({ content: [], finishReason: 'stop', usage: {}, warnings: [], request: {}, response: {} }),
      params: {
        prompt: [],
        tools: undefined,
        providerOptions: {}
      }
    })

    const parts = await collectStreamParts(wrappedResult.stream)
    
    // Extract all the IDs used in text events
    const textStartIds = parts.filter(p => p.type === 'text-start').map(p => p.id)
    const textEndIds = parts.filter(p => p.type === 'text-end').map(p => p.id)
    const textDeltaIds = parts.filter(p => p.type === 'text-delta').map(p => p.id)
    
    console.log('Fixed - Text start IDs:', textStartIds)
    console.log('Fixed - Text end IDs:', textEndIds)
    console.log('Fixed - Text delta IDs:', textDeltaIds)
    
    // With the fix: hermesToolMiddleware should control all text events with consistent IDs
    expect(textStartIds.length).toBe(1)
    expect(textEndIds.length).toBe(1)
    
    // All text events should use the same ID (generated by hermesToolMiddleware)
    const allTextIds = [...textStartIds, ...textEndIds, ...textDeltaIds]
    const uniqueIds = new Set(allTextIds)
    
    // Fixed: Only one unique ID should be used
    expect(uniqueIds.size).toBe(1)
    
    // And the start/end IDs should match
    expect(textStartIds[0]).toBe(textEndIds[0])
  })

  it('should not use the original Flower stream ID when middleware takes control', async () => {
    const originalFlowerStreamId = 'flower-test-123'
    
    const mockDoStream = async () => {
      const stream = createFixedFlowerStream(['Hello world!'], originalFlowerStreamId)
      return { stream }
    }

    // Apply hermesToolMiddleware
    const middleware = hermesToolMiddleware
    const wrappedResult = await middleware.wrapStream!({
      doStream: mockDoStream,
      doGenerate: async () => ({ content: [], finishReason: 'stop', usage: {}, warnings: [], request: {}, response: {} }),
      params: {
        prompt: [],
        tools: undefined,
        providerOptions: {}
      }
    })

    const parts = await collectStreamParts(wrappedResult.stream)
    
    // Find text-start and text-end events (text-delta events might still use original ID from Flower)
    const textStartEvents = parts.filter(p => p.type === 'text-start')
    const textEndEvents = parts.filter(p => p.type === 'text-end')
    
    // hermesToolMiddleware should generate its own IDs for text-start/text-end
    // and not use the original Flower stream ID
    expect(textStartEvents.length).toBe(1)
    expect(textEndEvents.length).toBe(1)
    
    const startId = textStartEvents[0].id
    const endId = textEndEvents[0].id
    
    // The start and end IDs should match (no mismatch)
    expect(startId).toBe(endId)
    
    // The middleware-generated ID should be different from the original Flower ID
    // (since middleware creates its own IDs)
    expect(startId).not.toBe(originalFlowerStreamId)
  })
})